const products = [
    {
      _id: "1",
      name: "oneplus 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 incredible",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: "2",
      name: "realme",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 incredible",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 0,
      rating: 3.5,
      numReviews: 5,
    },
    {
      _id: "3",
      name: "oneplus 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 incredible",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "4",
      name: "oneplus 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 ",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 0.1,
      numReviews: 12,
    },
    {
      _id: "5",
      name: "oneplus 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 ",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "6",
      name: "oneplus 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 ",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "7",
      name: "oneplus 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 ",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "8",
      name: "oneplusd 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusd Pro delivers game-changing performance for pros. Best phone of the year 2019 ",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "9",
      name: "oneplusb 7 Pro",
      image: "/images/oneplusb.jpg",
      description:
        "The new oneplusb Pro delivers game-changing performance for pros. Best phone of the year 2019 ",
      brand: "Apple",
      category: "Electronics",
      price: 1299,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
  ];
  
  export default products;